import FieldForm from '../FieldForm';
import { customMount } from '../../../../cypress/utils/mount';
describe('FieldForm', () => {
  it('render type Form', () => {
    customMount(FieldForm);
    cy.get('input[name="label"]').should('exist');
    cy.get('input[name="label"]').type('Developer Status');
    cy.get('input[name="fieldType"]').should('exist');
    cy.get('#fieldType-simple-select-outlined').click();
    cy.contains('Form').click();
    cy.get('#fieldType-simple-select-outlined').click();
    cy.contains('Form2').click();
    cy.get('#fieldType-simple-select-outlined').click();
    cy.contains('Text').click();
    cy.get('#fieldType-simple-select-outlined').click();
    cy.contains('Number').click();
    cy.get('#fieldType-simple-select-outlined').click();
    cy.contains('Password').click();
    cy.get('#fieldType-simple-select-outlined').click();
    cy.contains('Rich Textarea').click();
    cy.get('#fieldType-simple-select-outlined').click();
    cy.contains('Checkbox').click();
    cy.get('#fieldType-simple-select-outlined').click();
    cy.contains('Select').click();
    cy.get('#fieldType-simple-select-outlined').click();
    cy.contains('Email').click();
    cy.get('#fieldType-simple-select-outlined').click();
    cy.contains('Phone Number').click();
    cy.get('#fieldType-simple-select-outlined').click();
    cy.contains('Date').click();
    cy.get('#fieldType-simple-select-outlined').click();
    cy.contains('Date & Time').click();
    cy.get('#fieldType-simple-select-outlined').click();
    cy.contains('Media (Images/Video)').click();
    cy.get('#fieldType-simple-select-outlined').click();
    cy.contains('Address').click();
    cy.get('#fieldType-simple-select-outlined').click();
    cy.contains('Existing Type').click();
    cy.get('input[name="fieldLabel"]').type('Bug fixes');
    cy.get('input[type="checkbox"]').should('exist');
    cy.get('input[type="checkbox"]').click();
    cy.get('[data-testid=cancel-button').should('exist');
    cy.get('[data-testid=cancel-button').click();
    cy.get('[data-testid=save-button').should('exist');
    cy.get('[data-testid=save-button').click();
  });
});
