/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'us-east-1',
  aws_cognito_identity_pool_id: 'us-east-1:5ef810d9-5216-4eda-be67-43950fb9ea15',
  aws_cognito_region: 'us-east-1',
  aws_user_pools_id: 'us-east-1_rN5YhRWqL',
  aws_user_pools_web_client_id: '2ah1qndgorv25pic8jrcbgf7pp',
  oauth: {
    domain: 'drreamz-auth-dev.auth.us-east-1.amazoncognito.com',
    scope: ['phone', 'email', 'openid', 'profile', 'aws.cognito.signin.user.admin'],
    redirectSignIn: 'http://localhost:3000/,drreamz://,https://d27wezwiuran4j.cloudfront.net/',
    redirectSignOut: 'http://localhost:3000/,drreamz://,https://d27wezwiuran4j.cloudfront.net/',
    responseType: 'code',
  },
  federationTarget: 'COGNITO_USER_POOLS',
  graphqlEndpoint: 'https://jy2h0lqya4.execute-api.us-east-1.amazonaws.com/dev/graphql',
};

export default awsmobile;
