version: 0.2
phases:
  install:
    commands:
      - npm install -g yarn
      - npm install -g serverless
      - yarn install
  pre_build:
    commands:
      - yarn web:test
      - aws s3 sync s3://soozzi-cicd-bucket/vijaa/$BRANCH_NAME/.serverless packages/web/.serverless --delete
      - yarn web:build
      - echo Build completed on `date`
  build:
    commands:
      - yarn web:deploy

  post_build:
    commands:
      - aws s3 sync packages/web/.serverless s3://soozzi-cicd-bucket/vijaa/$BRANCH_NAME/.serverless --delete
      - echo Deploy completed on `date`
