const Diagram = (): any => {
  return {
    width: '100%',
    height: '645px',
    enableRtl: false,
    locale: 'en-US',
    enablePersistence: false,
    scrollSettings: {
      viewPortWidth: 987.390625,
      viewPortHeight: 645,
      currentZoom: 1,
      horizontalOffset: 0,
      verticalOffset: 0,
      padding: { left: 0, right: 0, top: 0, bottom: 0 },
      scrollLimit: 'Diagram',
      minZoom: 0.2,
      maxZoom: 30,
      canAutoScroll: false,
    },
    rulerSettings: {
      showRulers: false,
      horizontalRuler: { orientation: 'Horizontal', arrangeTick: null },
      verticalRuler: { orientation: 'Vertical', arrangeTick: null },
    },
    backgroundColor: 'transparent',
    dataSourceSettings: { crudAction: { read: '' }, dataManager: null, dataSource: null },
    mode: 'SVG',
    layers: [
      {
        objects: [
          'Start',
          'Alarm',
          'Ready',
          'Climb',
          'End',
          'Relay',
          'Hit',
          'connector1',
          'connector2',
          'connector3',
          'connector4',
          'connector5',
          'connector6',
          'connector7',
          '62e56083fb4cffd377f402a5mZb7d',
          'Link21I62TG',
        ],
        id: 'default_layer',
        visible: true,
        lock: false,
        zIndex: 0,
        objectZIndex: 15,
      },
    ],
    nodes: [
      {
        shape: { type: 'Flow', shape: 'Terminator' },
        ports: [
          {
            id: 'port1',
            shape: 'Circle',
            offset: { x: 0, y: 0.5 },
            inEdges: [],
            outEdges: [],
            height: 12,
            width: 12,
            margin: { right: 0, bottom: 0, left: 0, top: 0 },
            style: {
              fill: 'white',
              strokeColor: 'black',
              opacity: 1,
              strokeDashArray: '',
              strokeWidth: 1,
            },
            horizontalAlignment: 'Center',
            verticalAlignment: 'Center',
            visibility: 8,
            constraints: 24,
          },
          {
            id: 'port2',
            shape: 'Circle',
            offset: { x: 0.5, y: 1 },
            inEdges: [],
            outEdges: [],
            height: 12,
            width: 12,
            margin: { right: 0, bottom: 0, left: 0, top: 0 },
            style: {
              fill: 'white',
              strokeColor: 'black',
              opacity: 1,
              strokeDashArray: '',
              strokeWidth: 1,
            },
            horizontalAlignment: 'Center',
            verticalAlignment: 'Center',
            visibility: 8,
            constraints: 24,
          },
          {
            id: 'port3',
            shape: 'Circle',
            offset: { x: 1, y: 0.5 },
            inEdges: [],
            outEdges: [],
            height: 12,
            width: 12,
            margin: { right: 0, bottom: 0, left: 0, top: 0 },
            style: {
              fill: 'white',
              strokeColor: 'black',
              opacity: 1,
              strokeDashArray: '',
              strokeWidth: 1,
            },
            horizontalAlignment: 'Center',
            verticalAlignment: 'Center',
            visibility: 8,
            constraints: 24,
          },
          {
            id: 'port4',
            shape: 'Circle',
            offset: { x: 0.5, y: 0 },
            inEdges: [],
            outEdges: [],
            height: 12,
            width: 12,
            margin: { right: 0, bottom: 0, left: 0, top: 0 },
            style: {
              fill: 'white',
              strokeColor: 'black',
              opacity: 1,
              strokeDashArray: '',
              strokeWidth: 1,
            },
            horizontalAlignment: 'Center',
            verticalAlignment: 'Center',
            visibility: 8,
            constraints: 24,
          },
        ],
        id: 'Start',
        height: 50,
        width: 100,
        offsetX: 250,
        offsetY: 60,
        annotations: [
          {
            id: 'gTSC1',
            content: 'Start',
            annotationType: 'String',
            style: {
              strokeWidth: 0,
              strokeColor: 'transparent',
              fill: 'transparent',
              bold: false,
              textWrapping: 'WrapWithOverflow',
              color: 'black',
              whiteSpace: 'CollapseSpace',
              fontFamily: 'Arial',
              fontSize: 12,
              italic: false,
              opacity: 1,
              strokeDashArray: '',
              textAlign: 'Center',
              textOverflow: 'Wrap',
              textDecoration: 'None',
            },
            hyperlink: {
              link: '',
              hyperlinkOpenState: 'NewTab',
              content: '',
              textDecoration: 'None',
            },
            constraints: 4,
            visibility: true,
            rotateAngle: 0,
            margin: { right: 0, bottom: 0, left: 0, top: 0 },
            horizontalAlignment: 'Center',
            verticalAlignment: 'Center',
            offset: { x: 0.5, y: 0.5 },
          },
        ],
        style: {
          fill: '#d0f0f1',
          strokeColor: '#797979',
          gradient: { type: 'None' },
          strokeWidth: 1,
          strokeDashArray: '',
          opacity: 1,
        },
        zIndex: 0,
        container: null,
        visible: true,
        horizontalAlignment: 'Left',
        verticalAlignment: 'Top',
        backgroundColor: 'transparent',
        borderColor: 'none',
        borderWidth: 0,
        rotateAngle: 0,
        pivot: { x: 0.5, y: 0.5 },
        flip: 'None',
        wrapper: { actualSize: { width: 100, height: 50 }, offsetX: 250, offsetY: 60 },
        constraints: 5240814,
        isExpanded: true,
        expandIcon: { shape: 'None' },
        fixedUserHandles: [],
        flipMode: 'All',
        inEdges: [],
        outEdges: ['connector1'],
        parentId: '',
        processId: '',
        umlIndex: -1,
        isPhase: false,
        isLane: false,
      },
      {
        shape: { type: 'Flow', shape: 'Process' },
        ports: [
          {
            id: 'port1',
            shape: 'Circle',
            offset: { x: 0, y: 0.5 },
            inEdges: [],
            outEdges: [],
            height: 12,
            width: 12,
            margin: { right: 0, bottom: 0, left: 0, top: 0 },
            style: {
              fill: 'white',
              strokeColor: 'black',
              opacity: 1,
              strokeDashArray: '',
              strokeWidth: 1,
            },
            horizontalAlignment: 'Center',
            verticalAlignment: 'Center',
            visibility: 8,
            constraints: 24,
          },
          {
            id: 'port2',
            shape: 'Circle',
            offset: { x: 0.5, y: 1 },
            inEdges: [],
            outEdges: [],
            height: 12,
            width: 12,
            margin: { right: 0, bottom: 0, left: 0, top: 0 },
            style: {
              fill: 'white',
              strokeColor: 'black',
              opacity: 1,
              strokeDashArray: '',
              strokeWidth: 1,
            },
            horizontalAlignment: 'Center',
            verticalAlignment: 'Center',
            visibility: 8,
            constraints: 24,
          },
          {
            id: 'port3',
            shape: 'Circle',
            offset: { x: 1, y: 0.5 },
            inEdges: [],
            outEdges: [],
            height: 12,
            width: 12,
            margin: { right: 0, bottom: 0, left: 0, top: 0 },
            style: {
              fill: 'white',
              strokeColor: 'black',
              opacity: 1,
              strokeDashArray: '',
              strokeWidth: 1,
            },
            horizontalAlignment: 'Center',
            verticalAlignment: 'Center',
            visibility: 8,
            constraints: 24,
          },
          {
            id: 'port4',
            shape: 'Circle',
            offset: { x: 0.5, y: 0 },
            inEdges: [],
            outEdges: [],
            height: 12,
            width: 12,
            margin: { right: 0, bottom: 0, left: 0, top: 0 },
            style: {
              fill: 'white',
              strokeColor: 'black',
              opacity: 1,
              strokeDashArray: '',
              strokeWidth: 1,
            },
            horizontalAlignment: 'Center',
            verticalAlignment: 'Center',
            visibility: 8,
            constraints: 24,
          },
        ],
        id: 'Alarm',
        height: 50,
        width: 100,
        offsetX: 250,
        offsetY: 160,
        annotations: [
          {
            id: 'rgnyd',
            content: 'Alarm Rings',
            annotationType: 'String',
            style: {
              strokeWidth: 0,
              strokeColor: 'transparent',
              fill: 'transparent',
              bold: false,
              textWrapping: 'WrapWithOverflow',
              color: 'black',
              whiteSpace: 'CollapseSpace',
              fontFamily: 'Arial',
              fontSize: 12,
              italic: false,
              opacity: 1,
              strokeDashArray: '',
              textAlign: 'Center',
              textOverflow: 'Wrap',
              textDecoration: 'None',
            },
            hyperlink: {
              link: '',
              hyperlinkOpenState: 'NewTab',
              content: '',
              textDecoration: 'None',
            },
            constraints: 4,
            visibility: true,
            rotateAngle: 0,
            margin: { right: 0, bottom: 0, left: 0, top: 0 },
            horizontalAlignment: 'Center',
            verticalAlignment: 'Center',
            offset: { x: 0.5, y: 0.5 },
          },
        ],
        style: {
          fill: '#fbfdc5',
          strokeColor: '#797979',
          gradient: { type: 'None' },
          strokeWidth: 1,
          strokeDashArray: '',
          opacity: 1,
        },
        zIndex: 1,
        container: null,
        visible: true,
        horizontalAlignment: 'Left',
        verticalAlignment: 'Top',
        backgroundColor: 'transparent',
        borderColor: 'none',
        borderWidth: 0,
        rotateAngle: 0,
        pivot: { x: 0.5, y: 0.5 },
        flip: 'None',
        wrapper: { actualSize: { width: 100, height: 50 }, offsetX: 250, offsetY: 160 },
        constraints: 5240814,
        isExpanded: true,
        expandIcon: { shape: 'None' },
        fixedUserHandles: [],
        flipMode: 'All',
        inEdges: ['connector1', 'connector7'],
        outEdges: ['connector2'],
        parentId: '',
        processId: '',
        umlIndex: -1,
        isPhase: false,
        isLane: false,
      },
      {
        shape: { type: 'Flow', shape: 'Decision' },
        ports: [
          {
            id: 'port1',
            shape: 'Circle',
            offset: { x: 0, y: 0.5 },
            inEdges: [],
            outEdges: [],
            height: 12,
            width: 12,
            margin: { right: 0, bottom: 0, left: 0, top: 0 },
            style: {
              fill: 'white',
              strokeColor: 'black',
              opacity: 1,
              strokeDashArray: '',
              strokeWidth: 1,
            },
            horizontalAlignment: 'Center',
            verticalAlignment: 'Center',
            visibility: 8,
            constraints: 24,
          },
          {
            id: 'port2',
            shape: 'Circle',
            offset: { x: 0.5, y: 1 },
            inEdges: [],
            outEdges: [],
            height: 12,
            width: 12,
            margin: { right: 0, bottom: 0, left: 0, top: 0 },
            style: {
              fill: 'white',
              strokeColor: 'black',
              opacity: 1,
              strokeDashArray: '',
              strokeWidth: 1,
            },
            horizontalAlignment: 'Center',
            verticalAlignment: 'Center',
            visibility: 8,
            constraints: 24,
          },
          {
            id: 'port3',
            shape: 'Circle',
            offset: { x: 1, y: 0.5 },
            inEdges: [],
            outEdges: [],
            height: 12,
            width: 12,
            margin: { right: 0, bottom: 0, left: 0, top: 0 },
            style: {
              fill: 'white',
              strokeColor: 'black',
              opacity: 1,
              strokeDashArray: '',
              strokeWidth: 1,
            },
            horizontalAlignment: 'Center',
            verticalAlignment: 'Center',
            visibility: 8,
            constraints: 24,
          },
          {
            id: 'port4',
            shape: 'Circle',
            offset: { x: 0.5, y: 0 },
            inEdges: [],
            outEdges: [],
            height: 12,
            width: 12,
            margin: { right: 0, bottom: 0, left: 0, top: 0 },
            style: {
              fill: 'white',
              strokeColor: 'black',
              opacity: 1,
              strokeDashArray: '',
              strokeWidth: 1,
            },
            horizontalAlignment: 'Center',
            verticalAlignment: 'Center',
            visibility: 8,
            constraints: 24,
          },
        ],
        id: 'Ready',
        height: 80,
        width: 100,
        offsetX: 250,
        offsetY: 260,
        annotations: [
          {
            id: 'uawaH',
            content: 'Ready to Get Up?',
            margin: { top: 10, left: 10, right: 10, bottom: 10 },
            annotationType: 'String',
            style: {
              strokeWidth: 0,
              strokeColor: 'transparent',
              fill: 'transparent',
              bold: false,
              textWrapping: 'WrapWithOverflow',
              color: 'black',
              whiteSpace: 'CollapseSpace',
              fontFamily: 'Arial',
              fontSize: 12,
              italic: false,
              opacity: 1,
              strokeDashArray: '',
              textAlign: 'Center',
              textOverflow: 'Wrap',
              textDecoration: 'None',
            },
            hyperlink: {
              link: '',
              hyperlinkOpenState: 'NewTab',
              content: '',
              textDecoration: 'None',
            },
            constraints: 4,
            visibility: true,
            rotateAngle: 0,
            horizontalAlignment: 'Center',
            verticalAlignment: 'Center',
            offset: { x: 0.5, y: 0.5 },
          },
        ],
        style: {
          fill: '#c5efaf',
          strokeColor: '#797979',
          gradient: { type: 'None' },
          strokeWidth: 1,
          strokeDashArray: '',
          opacity: 1,
        },
        zIndex: 2,
        container: null,
        visible: true,
        horizontalAlignment: 'Left',
        verticalAlignment: 'Top',
        backgroundColor: 'transparent',
        borderColor: 'none',
        borderWidth: 0,
        rotateAngle: 0,
        pivot: { x: 0.5, y: 0.5 },
        flip: 'None',
        wrapper: { actualSize: { width: 100, height: 80 }, offsetX: 250, offsetY: 260 },
        constraints: 5240814,
        isExpanded: true,
        expandIcon: { shape: 'None' },
        fixedUserHandles: [],
        flipMode: 'All',
        tooltip: { openOn: 'Auto' },
        inEdges: ['connector2'],
        outEdges: ['connector3', 'connector5'],
        parentId: '',
        processId: '',
        umlIndex: -1,
        isPhase: false,
        isLane: false,
      },
      {
        shape: { type: 'Flow', shape: 'Process' },
        ports: [
          {
            id: 'port1',
            shape: 'Circle',
            offset: { x: 0, y: 0.5 },
            inEdges: [],
            outEdges: [],
            height: 12,
            width: 12,
            margin: { right: 0, bottom: 0, left: 0, top: 0 },
            style: {
              fill: 'white',
              strokeColor: 'black',
              opacity: 1,
              strokeDashArray: '',
              strokeWidth: 1,
            },
            horizontalAlignment: 'Center',
            verticalAlignment: 'Center',
            visibility: 8,
            constraints: 24,
          },
          {
            id: 'port2',
            shape: 'Circle',
            offset: { x: 0.5, y: 1 },
            inEdges: [],
            outEdges: [],
            height: 12,
            width: 12,
            margin: { right: 0, bottom: 0, left: 0, top: 0 },
            style: {
              fill: 'white',
              strokeColor: 'black',
              opacity: 1,
              strokeDashArray: '',
              strokeWidth: 1,
            },
            horizontalAlignment: 'Center',
            verticalAlignment: 'Center',
            visibility: 8,
            constraints: 24,
          },
          {
            id: 'port3',
            shape: 'Circle',
            offset: { x: 1, y: 0.5 },
            inEdges: [],
            outEdges: [],
            height: 12,
            width: 12,
            margin: { right: 0, bottom: 0, left: 0, top: 0 },
            style: {
              fill: 'white',
              strokeColor: 'black',
              opacity: 1,
              strokeDashArray: '',
              strokeWidth: 1,
            },
            horizontalAlignment: 'Center',
            verticalAlignment: 'Center',
            visibility: 8,
            constraints: 24,
          },
          {
            id: 'port4',
            shape: 'Circle',
            offset: { x: 0.5, y: 0 },
            inEdges: [],
            outEdges: [],
            height: 12,
            width: 12,
            margin: { right: 0, bottom: 0, left: 0, top: 0 },
            style: {
              fill: 'white',
              strokeColor: 'black',
              opacity: 1,
              strokeDashArray: '',
              strokeWidth: 1,
            },
            horizontalAlignment: 'Center',
            verticalAlignment: 'Center',
            visibility: 8,
            constraints: 24,
          },
        ],
        id: 'Climb',
        height: 50,
        width: 100,
        offsetX: 250,
        offsetY: 370,
        annotations: [
          {
            id: 'ItO4O',
            content: 'Climb Out of Bed',
            annotationType: 'String',
            style: {
              strokeWidth: 0,
              strokeColor: 'transparent',
              fill: 'transparent',
              bold: false,
              textWrapping: 'WrapWithOverflow',
              color: 'black',
              whiteSpace: 'CollapseSpace',
              fontFamily: 'Arial',
              fontSize: 12,
              italic: false,
              opacity: 1,
              strokeDashArray: '',
              textAlign: 'Center',
              textOverflow: 'Wrap',
              textDecoration: 'None',
            },
            hyperlink: {
              link: '',
              hyperlinkOpenState: 'NewTab',
              content: '',
              textDecoration: 'None',
            },
            constraints: 4,
            visibility: true,
            rotateAngle: 0,
            margin: { right: 0, bottom: 0, left: 0, top: 0 },
            horizontalAlignment: 'Center',
            verticalAlignment: 'Center',
            offset: { x: 0.5, y: 0.5 },
          },
        ],
        style: {
          fill: '#fbfdc5',
          strokeColor: '#797979',
          gradient: { type: 'None' },
          strokeWidth: 1,
          strokeDashArray: '',
          opacity: 1,
        },
        zIndex: 3,
        container: null,
        visible: true,
        horizontalAlignment: 'Left',
        verticalAlignment: 'Top',
        backgroundColor: 'transparent',
        borderColor: 'none',
        borderWidth: 0,
        rotateAngle: 0,
        pivot: { x: 0.5, y: 0.5 },
        flip: 'None',
        wrapper: { actualSize: { width: 100, height: 50 }, offsetX: 250, offsetY: 370 },
        constraints: 5240814,
        isExpanded: true,
        expandIcon: { shape: 'None' },
        fixedUserHandles: [],
        flipMode: 'All',
        tooltip: { openOn: 'Auto' },
        inEdges: ['connector3'],
        outEdges: ['connector4'],
        parentId: '',
        processId: '',
        umlIndex: -1,
        isPhase: false,
        isLane: false,
      },
      {
        shape: { type: 'Flow', shape: 'Terminator' },
        ports: [
          {
            id: 'port1',
            shape: 'Circle',
            offset: { x: 0, y: 0.5 },
            inEdges: [],
            outEdges: [],
            height: 12,
            width: 12,
            margin: { right: 0, bottom: 0, left: 0, top: 0 },
            style: {
              fill: 'white',
              strokeColor: 'black',
              opacity: 1,
              strokeDashArray: '',
              strokeWidth: 1,
            },
            horizontalAlignment: 'Center',
            verticalAlignment: 'Center',
            visibility: 8,
            constraints: 24,
          },
          {
            id: 'port2',
            shape: 'Circle',
            offset: { x: 0.5, y: 1 },
            inEdges: [],
            outEdges: [],
            height: 12,
            width: 12,
            margin: { right: 0, bottom: 0, left: 0, top: 0 },
            style: {
              fill: 'white',
              strokeColor: 'black',
              opacity: 1,
              strokeDashArray: '',
              strokeWidth: 1,
            },
            horizontalAlignment: 'Center',
            verticalAlignment: 'Center',
            visibility: 8,
            constraints: 24,
          },
          {
            id: 'port3',
            shape: 'Circle',
            offset: { x: 1, y: 0.5 },
            inEdges: [],
            outEdges: [],
            height: 12,
            width: 12,
            margin: { right: 0, bottom: 0, left: 0, top: 0 },
            style: {
              fill: 'white',
              strokeColor: 'black',
              opacity: 1,
              strokeDashArray: '',
              strokeWidth: 1,
            },
            horizontalAlignment: 'Center',
            verticalAlignment: 'Center',
            visibility: 8,
            constraints: 24,
          },
          {
            id: 'port4',
            shape: 'Circle',
            offset: { x: 0.5, y: 0 },
            inEdges: [],
            outEdges: [],
            height: 12,
            width: 12,
            margin: { right: 0, bottom: 0, left: 0, top: 0 },
            style: {
              fill: 'white',
              strokeColor: 'black',
              opacity: 1,
              strokeDashArray: '',
              strokeWidth: 1,
            },
            horizontalAlignment: 'Center',
            verticalAlignment: 'Center',
            visibility: 8,
            constraints: 24,
          },
        ],
        id: 'End',
        height: 50,
        width: 100,
        offsetX: 250,
        offsetY: 460,
        annotations: [
          {
            id: 'dGsie',
            content: 'End',
            annotationType: 'String',
            style: {
              strokeWidth: 0,
              strokeColor: 'transparent',
              fill: 'transparent',
              bold: false,
              textWrapping: 'WrapWithOverflow',
              color: 'black',
              whiteSpace: 'CollapseSpace',
              fontFamily: 'Arial',
              fontSize: 12,
              italic: false,
              opacity: 1,
              strokeDashArray: '',
              textAlign: 'Center',
              textOverflow: 'Wrap',
              textDecoration: 'None',
            },
            hyperlink: {
              link: '',
              hyperlinkOpenState: 'NewTab',
              content: '',
              textDecoration: 'None',
            },
            constraints: 4,
            visibility: true,
            rotateAngle: 0,
            margin: { right: 0, bottom: 0, left: 0, top: 0 },
            horizontalAlignment: 'Center',
            verticalAlignment: 'Center',
            offset: { x: 0.5, y: 0.5 },
          },
        ],
        style: {
          fill: '#d0f0f1',
          strokeColor: '#797979',
          gradient: { type: 'None' },
          strokeWidth: 1,
          strokeDashArray: '',
          opacity: 1,
        },
        zIndex: 4,
        container: null,
        visible: true,
        horizontalAlignment: 'Left',
        verticalAlignment: 'Top',
        backgroundColor: 'transparent',
        borderColor: 'none',
        borderWidth: 0,
        rotateAngle: 0,
        pivot: { x: 0.5, y: 0.5 },
        flip: 'None',
        wrapper: { actualSize: { width: 100, height: 50 }, offsetX: 250, offsetY: 460 },
        constraints: 5240814,
        isExpanded: true,
        expandIcon: { shape: 'None' },
        fixedUserHandles: [],
        flipMode: 'All',
        inEdges: ['connector4'],
        outEdges: [],
        parentId: '',
        processId: '',
        umlIndex: -1,
        isPhase: false,
        isLane: false,
      },
      {
        shape: { type: 'Flow', shape: 'Delay' },
        ports: [
          {
            id: 'port1',
            shape: 'Circle',
            offset: { x: 0, y: 0.5 },
            inEdges: [],
            outEdges: [],
            height: 12,
            width: 12,
            margin: { right: 0, bottom: 0, left: 0, top: 0 },
            style: {
              fill: 'white',
              strokeColor: 'black',
              opacity: 1,
              strokeDashArray: '',
              strokeWidth: 1,
            },
            horizontalAlignment: 'Center',
            verticalAlignment: 'Center',
            visibility: 8,
            constraints: 24,
          },
          {
            id: 'port2',
            shape: 'Circle',
            offset: { x: 0.5, y: 1 },
            inEdges: [],
            outEdges: [],
            height: 12,
            width: 12,
            margin: { right: 0, bottom: 0, left: 0, top: 0 },
            style: {
              fill: 'white',
              strokeColor: 'black',
              opacity: 1,
              strokeDashArray: '',
              strokeWidth: 1,
            },
            horizontalAlignment: 'Center',
            verticalAlignment: 'Center',
            visibility: 8,
            constraints: 24,
          },
          {
            id: 'port3',
            shape: 'Circle',
            offset: { x: 1, y: 0.5 },
            inEdges: [],
            outEdges: [],
            height: 12,
            width: 12,
            margin: { right: 0, bottom: 0, left: 0, top: 0 },
            style: {
              fill: 'white',
              strokeColor: 'black',
              opacity: 1,
              strokeDashArray: '',
              strokeWidth: 1,
            },
            horizontalAlignment: 'Center',
            verticalAlignment: 'Center',
            visibility: 8,
            constraints: 24,
          },
          {
            id: 'port4',
            shape: 'Circle',
            offset: { x: 0.5, y: 0 },
            inEdges: [],
            outEdges: [],
            height: 12,
            width: 12,
            margin: { right: 0, bottom: 0, left: 0, top: 0 },
            style: {
              fill: 'white',
              strokeColor: 'black',
              opacity: 1,
              strokeDashArray: '',
              strokeWidth: 1,
            },
            horizontalAlignment: 'Center',
            verticalAlignment: 'Center',
            visibility: 8,
            constraints: 24,
          },
        ],
        id: 'Relay',
        height: 50,
        width: 100,
        offsetX: 450,
        offsetY: 160,
        annotations: [
          {
            id: 'Ept4T',
            content: 'Relay',
            annotationType: 'String',
            style: {
              strokeWidth: 0,
              strokeColor: 'transparent',
              fill: 'transparent',
              bold: false,
              textWrapping: 'WrapWithOverflow',
              color: 'black',
              whiteSpace: 'CollapseSpace',
              fontFamily: 'Arial',
              fontSize: 12,
              italic: false,
              opacity: 1,
              strokeDashArray: '',
              textAlign: 'Center',
              textOverflow: 'Wrap',
              textDecoration: 'None',
            },
            hyperlink: {
              link: '',
              hyperlinkOpenState: 'NewTab',
              content: '',
              textDecoration: 'None',
            },
            constraints: 4,
            visibility: true,
            rotateAngle: 0,
            margin: { right: 0, bottom: 0, left: 0, top: 0 },
            horizontalAlignment: 'Center',
            verticalAlignment: 'Center',
            offset: { x: 0.5, y: 0.5 },
          },
        ],
        style: {
          fill: '#f8eee5',
          strokeColor: '#797979',
          gradient: { type: 'None' },
          strokeWidth: 1,
          strokeDashArray: '',
          opacity: 1,
        },
        zIndex: 5,
        container: null,
        visible: true,
        horizontalAlignment: 'Left',
        verticalAlignment: 'Top',
        backgroundColor: 'transparent',
        borderColor: 'none',
        borderWidth: 0,
        rotateAngle: 0,
        pivot: { x: 0.5, y: 0.5 },
        flip: 'None',
        wrapper: { actualSize: { width: 100, height: 50 }, offsetX: 450, offsetY: 160 },
        constraints: 5240814,
        isExpanded: true,
        expandIcon: { shape: 'None' },
        fixedUserHandles: [],
        flipMode: 'All',
        inEdges: ['connector6'],
        outEdges: ['connector7'],
        parentId: '',
        processId: '',
        umlIndex: -1,
        isPhase: false,
        isLane: false,
      },
      {
        shape: { type: 'Flow', shape: 'Process' },
        ports: [
          {
            id: 'port1',
            shape: 'Circle',
            offset: { x: 0, y: 0.5 },
            inEdges: [],
            outEdges: [],
            height: 12,
            width: 12,
            margin: { right: 0, bottom: 0, left: 0, top: 0 },
            style: {
              fill: 'white',
              strokeColor: 'black',
              opacity: 1,
              strokeDashArray: '',
              strokeWidth: 1,
            },
            horizontalAlignment: 'Center',
            verticalAlignment: 'Center',
            visibility: 8,
            constraints: 24,
          },
          {
            id: 'port2',
            shape: 'Circle',
            offset: { x: 0.5, y: 1 },
            inEdges: [],
            outEdges: [],
            height: 12,
            width: 12,
            margin: { right: 0, bottom: 0, left: 0, top: 0 },
            style: {
              fill: 'white',
              strokeColor: 'black',
              opacity: 1,
              strokeDashArray: '',
              strokeWidth: 1,
            },
            horizontalAlignment: 'Center',
            verticalAlignment: 'Center',
            visibility: 8,
            constraints: 24,
          },
          {
            id: 'port3',
            shape: 'Circle',
            offset: { x: 1, y: 0.5 },
            inEdges: [],
            outEdges: [],
            height: 12,
            width: 12,
            margin: { right: 0, bottom: 0, left: 0, top: 0 },
            style: {
              fill: 'white',
              strokeColor: 'black',
              opacity: 1,
              strokeDashArray: '',
              strokeWidth: 1,
            },
            horizontalAlignment: 'Center',
            verticalAlignment: 'Center',
            visibility: 8,
            constraints: 24,
          },
          {
            id: 'port4',
            shape: 'Circle',
            offset: { x: 0.5, y: 0 },
            inEdges: [],
            outEdges: [],
            height: 12,
            width: 12,
            margin: { right: 0, bottom: 0, left: 0, top: 0 },
            style: {
              fill: 'white',
              strokeColor: 'black',
              opacity: 1,
              strokeDashArray: '',
              strokeWidth: 1,
            },
            horizontalAlignment: 'Center',
            verticalAlignment: 'Center',
            visibility: 8,
            constraints: 24,
          },
        ],
        id: 'Hit',
        height: 50,
        width: 100,
        offsetX: 450,
        offsetY: 260,
        annotations: [
          {
            id: 'XHoI1',
            content: 'Hit Snooze Button',
            margin: { top: 10, left: 10, right: 10, bottom: 10 },
            annotationType: 'String',
            style: {
              strokeWidth: 0,
              strokeColor: 'transparent',
              fill: 'transparent',
              bold: false,
              textWrapping: 'WrapWithOverflow',
              color: 'black',
              whiteSpace: 'CollapseSpace',
              fontFamily: 'Arial',
              fontSize: 12,
              italic: false,
              opacity: 1,
              strokeDashArray: '',
              textAlign: 'Center',
              textOverflow: 'Wrap',
              textDecoration: 'None',
            },
            hyperlink: {
              link: '',
              hyperlinkOpenState: 'NewTab',
              content: '',
              textDecoration: 'None',
            },
            constraints: 4,
            visibility: true,
            rotateAngle: 0,
            horizontalAlignment: 'Center',
            verticalAlignment: 'Center',
            offset: { x: 0.5, y: 0.5 },
          },
        ],
        style: {
          fill: '#fbfdc5',
          strokeColor: '#797979',
          gradient: { type: 'None' },
          strokeWidth: 1,
          strokeDashArray: '',
          opacity: 1,
        },
        zIndex: 6,
        container: null,
        visible: true,
        horizontalAlignment: 'Left',
        verticalAlignment: 'Top',
        backgroundColor: 'transparent',
        borderColor: 'none',
        borderWidth: 0,
        rotateAngle: 0,
        pivot: { x: 0.5, y: 0.5 },
        flip: 'None',
        wrapper: { actualSize: { width: 100, height: 50 }, offsetX: 450, offsetY: 260 },
        constraints: 5240814,
        isExpanded: true,
        expandIcon: { shape: 'None' },
        fixedUserHandles: [],
        flipMode: 'All',
        inEdges: ['connector5'],
        outEdges: ['connector6'],
        parentId: '',
        processId: '',
        umlIndex: -1,
        isPhase: false,
        isLane: false,
      },
      {
        shape: {
          type: 'Text',
          content: 'ARJAV SETHI',
          margin: { right: 0, bottom: 0, left: 0, top: 0 },
        },
        ports: [
          {
            inEdges: [],
            outEdges: [],
            id: 'port1',
            shape: 'Circle',
            offset: { x: 0, y: 0.5 },
            height: 12,
            width: 12,
            margin: { right: 0, bottom: 0, left: 0, top: 0 },
            style: {
              fill: 'white',
              strokeColor: 'black',
              opacity: 1,
              strokeDashArray: '',
              strokeWidth: 1,
            },
            horizontalAlignment: 'Center',
            verticalAlignment: 'Center',
            visibility: 8,
            constraints: 24,
          },
          {
            inEdges: [],
            outEdges: [],
            id: 'port2',
            shape: 'Circle',
            offset: { x: 0.5, y: 1 },
            height: 12,
            width: 12,
            margin: { right: 0, bottom: 0, left: 0, top: 0 },
            style: {
              fill: 'white',
              strokeColor: 'black',
              opacity: 1,
              strokeDashArray: '',
              strokeWidth: 1,
            },
            horizontalAlignment: 'Center',
            verticalAlignment: 'Center',
            visibility: 8,
            constraints: 24,
          },
          {
            inEdges: [],
            outEdges: [],
            id: 'port3',
            shape: 'Circle',
            offset: { x: 1, y: 0.5 },
            height: 12,
            width: 12,
            margin: { right: 0, bottom: 0, left: 0, top: 0 },
            style: {
              fill: 'white',
              strokeColor: 'black',
              opacity: 1,
              strokeDashArray: '',
              strokeWidth: 1,
            },
            horizontalAlignment: 'Center',
            verticalAlignment: 'Center',
            visibility: 8,
            constraints: 24,
          },
          {
            inEdges: [],
            outEdges: [],
            id: 'port4',
            shape: 'Circle',
            offset: { x: 0.5, y: 0 },
            height: 12,
            width: 12,
            margin: { right: 0, bottom: 0, left: 0, top: 0 },
            style: {
              fill: 'white',
              strokeColor: 'black',
              opacity: 1,
              strokeDashArray: '',
              strokeWidth: 1,
            },
            horizontalAlignment: 'Center',
            verticalAlignment: 'Center',
            visibility: 8,
            constraints: 24,
          },
        ],
        id: '62e56083fb4cffd377f402a5mZb7d',
        data: { _id: '62e56083fb4cffd377f402a5' },
        constraints: 13629422,
        style: {
          fill: '#FDFE7D',
          fontSize: 12,
          strokeColor: 'white',
          strokeWidth: 1,
          strokeDashArray: '',
          opacity: 1,
          gradient: { type: 'None' },
          fontFamily: 'Arial',
          textOverflow: 'Wrap',
          textDecoration: 'None',
          whiteSpace: 'CollapseSpace',
          textWrapping: 'WrapWithOverflow',
          textAlign: 'Center',
          color: 'black',
          italic: false,
          bold: false,
        },
        fixedUserHandles: [
          {
            margin: { right: 20, top: 5, bottom: 0, left: 0 },
            pathData:
              'M60.3,18H27.5c-3,0-5.5,2.4-5.5,5.5v38.2h5.5V23.5h32.7V18z M68.5,28.9h-30c-3,0-5.5,2.4-5.5,5.5v38.2c0,3,2.4,5.5,5.5,5.5h30c3,0,5.5-2.4,5.5-5.5V34.4C73.9,31.4,71.5,28.9,68.5,28.9z M68.5,72.5h-30V34.4h30V72.5z',
            id: 'Hx7o6',
            height: 10,
            width: 10,
            handleStrokeColor: 'transparent',
            fill: 'transparent',
            handleStrokeWidth: 1,
            visibility: true,
            cornerRadius: 0,
            offset: { x: 0, y: 0 },
            iconStrokeColor: 'black',
            iconStrokeWidth: 0,
          },
        ],
        width: 100,
        height: 100,
        container: null,
        offsetX: 468.390625,
        offsetY: 423,
        visible: true,
        horizontalAlignment: 'Left',
        verticalAlignment: 'Top',
        backgroundColor: 'transparent',
        borderColor: 'none',
        borderWidth: 0,
        rotateAngle: 0,
        pivot: { x: 0.5, y: 0.5 },
        flip: 'None',
        wrapper: { actualSize: { width: 100, height: 100 }, offsetX: 468.390625, offsetY: 423 },
        zIndex: 14,
        annotations: [
          {
            id: '0annotation',
            style: {
              strokeWidth: 0,
              strokeColor: 'transparent',
              fill: 'transparent',
              color: 'black',
              bold: false,
              textWrapping: 'WrapWithOverflow',
              whiteSpace: 'CollapseSpace',
              fontFamily: 'Arial',
              fontSize: 12,
              italic: false,
              opacity: 1,
              strokeDashArray: '',
              textAlign: 'Center',
              textOverflow: 'Wrap',
              textDecoration: 'None',
            },
            content: '',
            annotationType: 'String',
            hyperlink: {
              link: '',
              hyperlinkOpenState: 'NewTab',
              content: '',
              textDecoration: 'None',
            },
            constraints: 4,
            visibility: true,
            rotateAngle: 0,
            margin: { right: 0, bottom: 0, left: 0, top: 0 },
            horizontalAlignment: 'Center',
            verticalAlignment: 'Center',
            offset: { x: 0.5, y: 0.5 },
          },
        ],
        flipMode: 'All',
        isExpanded: true,
        expandIcon: { shape: 'None' },
        tooltip: { openOn: 'Auto' },
        inEdges: ['Link21I62TG'],
        outEdges: [],
        parentId: '',
        processId: '',
        umlIndex: -1,
        isPhase: false,
        isLane: false,
      },
    ],
    connectors: [
      {
        shape: { type: 'None' },
        id: 'connector1',
        sourceID: 'Start',
        targetID: 'Alarm',
        annotations: [],
        zIndex: 7,
        targetDecorator: {
          shape: 'Arrow',
          height: 10,
          width: 10,
          style: {
            fill: '#797979',
            strokeColor: '#797979',
            strokeWidth: 1,
            strokeDashArray: '',
            opacity: 1,
            gradient: { type: 'None' },
          },
          pivot: { x: 0, y: 0.5 },
        },
        style: {
          strokeWidth: 1,
          strokeColor: '#797979',
          fill: 'transparent',
          strokeDashArray: '',
          opacity: 1,
          gradient: { type: 'None' },
        },
        segments: [{ type: 'Orthogonal', direction: null }],
        sourcePortID: '',
        targetPortID: '',
        type: 'Orthogonal',
        sourcePadding: 0,
        targetPadding: 0,
        targetPoint: { x: 250, y: 135 },
        connectorSpacing: 13,
        sourcePoint: { x: 250, y: 85 },
        sourceDecorator: {
          shape: 'None',
          width: 10,
          height: 10,
          pivot: { x: 0, y: 0.5 },
          style: {
            fill: 'black',
            strokeColor: 'black',
            strokeWidth: 1,
            strokeDashArray: '',
            opacity: 1,
            gradient: { type: 'None' },
          },
        },
        cornerRadius: 0,
        wrapper: { actualSize: { width: 0, height: 50 }, offsetX: 250, offsetY: 110 },
        fixedUserHandles: [],
        visible: true,
        parentId: '',
      },
      {
        shape: { type: 'None' },
        id: 'connector2',
        sourceID: 'Alarm',
        targetID: 'Ready',
        annotations: [],
        zIndex: 8,
        targetDecorator: {
          shape: 'Arrow',
          height: 10,
          width: 10,
          style: {
            fill: '#797979',
            strokeColor: '#797979',
            strokeWidth: 1,
            strokeDashArray: '',
            opacity: 1,
            gradient: { type: 'None' },
          },
          pivot: { x: 0, y: 0.5 },
        },
        style: {
          strokeWidth: 1,
          strokeColor: '#797979',
          fill: 'transparent',
          strokeDashArray: '',
          opacity: 1,
          gradient: { type: 'None' },
        },
        segments: [{ type: 'Orthogonal', direction: null }],
        sourcePortID: '',
        targetPortID: '',
        type: 'Orthogonal',
        sourcePadding: 0,
        targetPadding: 0,
        targetPoint: { x: 250, y: 222.07 },
        connectorSpacing: 13,
        sourcePoint: { x: 250, y: 185 },
        sourceDecorator: {
          shape: 'None',
          width: 10,
          height: 10,
          pivot: { x: 0, y: 0.5 },
          style: {
            fill: 'black',
            strokeColor: 'black',
            strokeWidth: 1,
            strokeDashArray: '',
            opacity: 1,
            gradient: { type: 'None' },
          },
        },
        cornerRadius: 0,
        wrapper: {
          actualSize: { width: 0, height: 37.06999999999999 },
          offsetX: 250,
          offsetY: 203.535,
        },
        fixedUserHandles: [],
        visible: true,
        constraints: 470590,
        hitPadding: 10,
        parentId: '',
      },
      {
        shape: { type: 'None' },
        id: 'connector3',
        sourceID: 'Ready',
        targetID: 'Climb',
        annotations: [
          {
            id: 'dKJXU',
            content: 'Yes',
            style: {
              strokeWidth: 0,
              strokeColor: 'transparent',
              fill: 'white',
              strokeDashArray: '',
              opacity: 1,
              gradient: { type: 'None' },
              fontSize: 12,
              fontFamily: 'Arial',
              textOverflow: 'Wrap',
              textDecoration: 'None',
              whiteSpace: 'CollapseSpace',
              textWrapping: 'WrapWithOverflow',
              textAlign: 'Center',
              color: 'black',
              italic: false,
              bold: false,
            },
            annotationType: 'String',
            constraints: 4,
            visibility: true,
            rotateAngle: 0,
            horizontalAlignment: 'Center',
            verticalAlignment: 'Center',
            margin: { left: 0, right: 0, bottom: 0, top: 0 },
            offset: 0.5,
            alignment: 'Center',
            segmentAngle: false,
          },
        ],
        zIndex: 9,
        targetDecorator: {
          shape: 'Arrow',
          height: 10,
          width: 10,
          style: {
            fill: '#797979',
            strokeColor: '#797979',
            strokeWidth: 1,
            strokeDashArray: '',
            opacity: 1,
            gradient: { type: 'None' },
          },
          pivot: { x: 0, y: 0.5 },
        },
        style: {
          strokeWidth: 1,
          strokeColor: '#797979',
          fill: 'transparent',
          strokeDashArray: '',
          opacity: 1,
          gradient: { type: 'None' },
        },
        segments: [{ type: 'Orthogonal', direction: null }],
        sourcePortID: '',
        targetPortID: '',
        type: 'Orthogonal',
        sourcePadding: 0,
        targetPadding: 0,
        targetPoint: { x: 250, y: 345 },
        connectorSpacing: 13,
        sourcePoint: { x: 250, y: 296.99 },
        sourceDecorator: {
          shape: 'None',
          width: 10,
          height: 10,
          pivot: { x: 0, y: 0.5 },
          style: {
            fill: 'black',
            strokeColor: 'black',
            strokeWidth: 1,
            strokeDashArray: '',
            opacity: 1,
            gradient: { type: 'None' },
          },
        },
        cornerRadius: 0,
        wrapper: {
          actualSize: { width: 0, height: 48.00999999999999 },
          offsetX: 250,
          offsetY: 320.995,
        },
        fixedUserHandles: [],
        visible: true,
        constraints: 470590,
        hitPadding: 10,
        parentId: '',
      },
      {
        shape: { type: 'None' },
        id: 'connector4',
        sourceID: 'Climb',
        targetID: 'End',
        annotations: [],
        zIndex: 10,
        targetDecorator: {
          shape: 'Arrow',
          height: 10,
          width: 10,
          style: {
            fill: '#797979',
            strokeColor: '#797979',
            strokeWidth: 1,
            strokeDashArray: '',
            opacity: 1,
            gradient: { type: 'None' },
          },
          pivot: { x: 0, y: 0.5 },
        },
        style: {
          strokeWidth: 1,
          strokeColor: '#797979',
          fill: 'transparent',
          strokeDashArray: '',
          opacity: 1,
          gradient: { type: 'None' },
        },
        segments: [{ type: 'Orthogonal', direction: null }],
        sourcePortID: '',
        targetPortID: '',
        type: 'Orthogonal',
        sourcePadding: 0,
        targetPadding: 0,
        targetPoint: { x: 250, y: 435 },
        connectorSpacing: 13,
        sourcePoint: { x: 250, y: 395 },
        sourceDecorator: {
          shape: 'None',
          width: 10,
          height: 10,
          pivot: { x: 0, y: 0.5 },
          style: {
            fill: 'black',
            strokeColor: 'black',
            strokeWidth: 1,
            strokeDashArray: '',
            opacity: 1,
            gradient: { type: 'None' },
          },
        },
        cornerRadius: 0,
        wrapper: { actualSize: { width: 0, height: 40 }, offsetX: 250, offsetY: 415 },
        fixedUserHandles: [],
        visible: true,
        constraints: 470590,
        hitPadding: 10,
        tooltip: { openOn: 'Auto' },
        parentId: '',
      },
      {
        shape: { type: 'None' },
        id: 'connector5',
        sourceID: 'Ready',
        targetID: 'Hit',
        annotations: [
          {
            id: 'LGPg8',
            content: 'No',
            style: {
              strokeWidth: 0,
              strokeColor: 'transparent',
              fill: 'white',
              strokeDashArray: '',
              opacity: 1,
              gradient: { type: 'None' },
              fontSize: 12,
              fontFamily: 'Arial',
              textOverflow: 'Wrap',
              textDecoration: 'None',
              whiteSpace: 'CollapseSpace',
              textWrapping: 'WrapWithOverflow',
              textAlign: 'Center',
              color: 'black',
              italic: false,
              bold: false,
            },
            annotationType: 'String',
            constraints: 4,
            visibility: true,
            rotateAngle: 0,
            horizontalAlignment: 'Center',
            verticalAlignment: 'Center',
            margin: { left: 0, right: 0, bottom: 0, top: 0 },
            offset: 0.5,
            alignment: 'Center',
            segmentAngle: false,
          },
        ],
        zIndex: 11,
        targetDecorator: {
          shape: 'Arrow',
          height: 10,
          width: 10,
          style: {
            fill: '#797979',
            strokeColor: '#797979',
            strokeWidth: 1,
            strokeDashArray: '',
            opacity: 1,
            gradient: { type: 'None' },
          },
          pivot: { x: 0, y: 0.5 },
        },
        style: {
          strokeWidth: 1,
          strokeColor: '#797979',
          fill: 'transparent',
          strokeDashArray: '',
          opacity: 1,
          gradient: { type: 'None' },
        },
        segments: [{ type: 'Orthogonal', direction: null }],
        sourcePortID: '',
        targetPortID: '',
        type: 'Orthogonal',
        sourcePadding: 0,
        targetPadding: 0,
        targetPoint: { x: 400, y: 260 },
        connectorSpacing: 13,
        sourcePoint: { x: 300, y: 260 },
        sourceDecorator: {
          shape: 'None',
          width: 10,
          height: 10,
          pivot: { x: 0, y: 0.5 },
          style: {
            fill: 'black',
            strokeColor: 'black',
            strokeWidth: 1,
            strokeDashArray: '',
            opacity: 1,
            gradient: { type: 'None' },
          },
        },
        cornerRadius: 0,
        wrapper: { actualSize: { width: 100, height: 0 }, offsetX: 350, offsetY: 260 },
        fixedUserHandles: [],
        visible: true,
        constraints: 470590,
        hitPadding: 10,
        parentId: '',
      },
      {
        shape: { type: 'None' },
        id: 'connector6',
        sourceID: 'Hit',
        targetID: 'Relay',
        annotations: [],
        zIndex: 12,
        targetDecorator: {
          shape: 'Arrow',
          height: 10,
          width: 10,
          style: {
            fill: '#797979',
            strokeColor: '#797979',
            strokeWidth: 1,
            strokeDashArray: '',
            opacity: 1,
            gradient: { type: 'None' },
          },
          pivot: { x: 0, y: 0.5 },
        },
        style: {
          strokeWidth: 1,
          strokeColor: '#797979',
          fill: 'transparent',
          strokeDashArray: '',
          opacity: 1,
          gradient: { type: 'None' },
        },
        segments: [{ type: 'Orthogonal', direction: null }],
        sourcePortID: '',
        targetPortID: '',
        type: 'Orthogonal',
        sourcePadding: 0,
        targetPadding: 0,
        targetPoint: { x: 450, y: 185 },
        connectorSpacing: 13,
        sourcePoint: { x: 450, y: 235 },
        sourceDecorator: {
          shape: 'None',
          width: 10,
          height: 10,
          pivot: { x: 0, y: 0.5 },
          style: {
            fill: 'black',
            strokeColor: 'black',
            strokeWidth: 1,
            strokeDashArray: '',
            opacity: 1,
            gradient: { type: 'None' },
          },
        },
        cornerRadius: 0,
        wrapper: { actualSize: { width: 0, height: 50 }, offsetX: 450, offsetY: 210 },
        fixedUserHandles: [],
        visible: true,
        constraints: 470590,
        hitPadding: 10,
        parentId: '',
      },
      {
        shape: { type: 'None' },
        id: 'connector7',
        sourceID: 'Relay',
        targetID: 'Alarm',
        annotations: [],
        zIndex: 13,
        targetDecorator: {
          shape: 'Arrow',
          height: 10,
          width: 10,
          style: {
            fill: '#797979',
            strokeColor: '#797979',
            strokeWidth: 1,
            strokeDashArray: '',
            opacity: 1,
            gradient: { type: 'None' },
          },
          pivot: { x: 0, y: 0.5 },
        },
        style: {
          strokeWidth: 1,
          strokeColor: '#797979',
          fill: 'transparent',
          strokeDashArray: '',
          opacity: 1,
          gradient: { type: 'None' },
        },
        segments: [{ type: 'Orthogonal', direction: null }],
        sourcePortID: '',
        targetPortID: '',
        type: 'Orthogonal',
        sourcePadding: 0,
        targetPadding: 0,
        targetPoint: { x: 300, y: 160 },
        connectorSpacing: 13,
        sourcePoint: { x: 400, y: 160 },
        sourceDecorator: {
          shape: 'None',
          width: 10,
          height: 10,
          pivot: { x: 0, y: 0.5 },
          style: {
            fill: 'black',
            strokeColor: 'black',
            strokeWidth: 1,
            strokeDashArray: '',
            opacity: 1,
            gradient: { type: 'None' },
          },
        },
        cornerRadius: 0,
        wrapper: { actualSize: { width: 100, height: 0 }, offsetX: 350, offsetY: 160 },
        fixedUserHandles: [],
        visible: true,
        constraints: 470590,
        hitPadding: 10,
        tooltip: { openOn: 'Auto' },
        parentId: '',
      },
      {
        shape: { type: 'None' },
        id: 'Link21I62TG',
        type: 'Straight',
        sourcePoint: { x: 453.39, y: 272 },
        targetPoint: { x: 463.42, y: 373 },
        targetDecorator: {
          shape: 'Arrow',
          style: {
            fill: '#757575',
            strokeColor: '#757575',
            strokeWidth: 1,
            strokeDashArray: '',
            opacity: 1,
            gradient: { type: 'None' },
          },
          width: 10,
          height: 10,
          pivot: { x: 0, y: 0.5 },
        },
        style: {
          strokeWidth: 1,
          strokeColor: '#757575',
          fill: 'transparent',
          strokeDashArray: '',
          opacity: 1,
          gradient: { type: 'None' },
        },
        sourcePortID: '',
        targetPortID: '',
        sourceID: '',
        targetID: '62e56083fb4cffd377f402a5mZb7d',
        flip: 'None',
        connectorSpacing: 13,
        segments: [{ type: 'Straight', point: { x: 0, y: 0 } }],
        sourceDecorator: {
          shape: 'None',
          width: 10,
          height: 10,
          pivot: { x: 0, y: 0.5 },
          style: {
            fill: 'black',
            strokeColor: 'black',
            strokeWidth: 1,
            strokeDashArray: '',
            opacity: 1,
            gradient: { type: 'None' },
          },
        },
        cornerRadius: 0,
        wrapper: {
          actualSize: { width: 10.03000000000003, height: 101 },
          offsetX: 458.405,
          offsetY: 322.5,
        },
        annotations: [],
        fixedUserHandles: [],
        zIndex: 15,
        visible: true,
        constraints: 470590,
        connectionPadding: 0,
        hitPadding: 10,
        tooltip: { openOn: 'Auto' },
        targetPadding: 0,
        sourcePadding: 0,
        parentId: '',
      },
    ],
    layout: { type: 'None', enableRouting: false },
    pageSettings: {
      orientation: 'Landscape',
      height: null,
      width: null,
      background: { source: '', color: 'transparent' },
      showPageBreaks: false,
      fitOptions: { canFit: false },
      boundaryConstraints: 'Infinity',
    },
    snapSettings: {
      constraints: 31,
      gridType: 'Lines',
      verticalGridlines: {
        lineIntervals: [
          1,
          9,
          0.25,
          9.75,
          0.25,
          9.75,
          0.25,
          9.75,
          0.25,
          9.75,
          0.25,
          9.75,
          0.25,
          9.75,
          0.25,
          9.75,
          0.25,
          9.75,
          0.25,
          9.75,
        ],
        snapIntervals: [20],
        lineDashArray: '',
        lineColor: '#e0e0e0',
      },
      horizontalGridlines: {
        lineIntervals: [
          1,
          9,
          0.25,
          9.75,
          0.25,
          9.75,
          0.25,
          9.75,
          0.25,
          9.75,
          0.25,
          9.75,
          0.25,
          9.75,
          0.25,
          9.75,
          0.25,
          9.75,
          0.25,
          9.75,
        ],
        snapIntervals: [20],
        lineDashArray: '',
        lineColor: '#e0e0e0',
      },
    },
    selectedItems: {
      nodes: [],
      connectors: [],
      constraints: 16382,
      selectedObjects: [],
      userHandles: [],
      rotateAngle: 0,
      pivot: { x: 0.5, y: 0.5 },
      width: 0,
      height: 0,
      offsetX: 0,
      offsetY: 0,
      wrapper: null,
    },
    constraints: 500,
    basicElements: [],
    tooltip: { content: '' },
    commandManager: { commands: [] },
    tool: 3,
    bridgeDirection: 'Top',
    diagramSettings: { inversedAlignment: true },
    customCursor: [],
    enableConnectorSplit: false,
    version: 17.1,
  };
};
export default Diagram;
