export const defaultDiagram = {
  width: '100%',
  height: '645px',
  nodes: [
    {
      shape: { type: 'Flow', shape: 'Terminator' },
      ports: [],
      id: 'Start',
      height: 50,
      width: 100,
      offsetX: 250,
      offsetY: 60,
      annotations: [
        {
          id: 'gTSC1',
          content: 'Start',
          annotationType: 'String',
          style: {
            strokeWidth: 0,
            strokeColor: 'transparent',
            fill: 'transparent',
            bold: false,
            textWrapping: 'WrapWithOverflow',
            color: 'black',
            whiteSpace: 'CollapseSpace',
            fontFamily: 'Arial',
            fontSize: 12,
            italic: false,
            opacity: 1,
            strokeDashArray: '',
            textAlign: 'Center',
            textOverflow: 'Wrap',
            textDecoration: 'None',
          },
          hyperlink: {
            link: '',
            hyperlinkOpenState: 'NewTab',
            content: '',
            textDecoration: 'None',
          },
          constraints: 4,
          visibility: true,
          rotateAngle: 0,
          margin: { right: 0, bottom: 0, left: 0, top: 0 },
          horizontalAlignment: 'Center',
          verticalAlignment: 'Center',
          offset: { x: 0.5, y: 0.5 },
        },
      ],
      style: {
        fill: '#d0f0f1',
        strokeColor: '#797979',
        gradient: { type: 'None' },
        strokeWidth: 1,
        strokeDashArray: '',
        opacity: 1,
      },
      zIndex: 0,
      container: null,
      visible: true,
      horizontalAlignment: 'Left',
      verticalAlignment: 'Top',
      backgroundColor: 'transparent',
      borderColor: 'none',
      borderWidth: 0,
      rotateAngle: 0,
      pivot: { x: 0.5, y: 0.5 },
      margin: {},
      flip: 'None',
      wrapper: {
        actualSize: { width: 100, height: 50 },
        offsetX: 250,
        offsetY: 60,
      },
      constraints: 5240814,
      isExpanded: true,
      expandIcon: { shape: 'None' },
      fixedUserHandles: [],
      inEdges: [],
      outEdges: ['connector1'],
      parentId: '',
      processId: '',
      umlIndex: -1,
      isPhase: false,
      isLane: false,
    },
    {
      shape: { type: 'Flow', shape: 'Process' },
      ports: [],
      id: 'Alarm',
      height: 50,
      width: 100,
      offsetX: 250,
      offsetY: 160,
      annotations: [
        {
          id: 'rgnyd',
          content: 'Alarm Rings',
          annotationType: 'String',
          style: {
            strokeWidth: 0,
            strokeColor: 'transparent',
            fill: 'transparent',
            bold: false,
            textWrapping: 'WrapWithOverflow',
            color: 'black',
            whiteSpace: 'CollapseSpace',
            fontFamily: 'Arial',
            fontSize: 12,
            italic: false,
            opacity: 1,
            strokeDashArray: '',
            textAlign: 'Center',
            textOverflow: 'Wrap',
            textDecoration: 'None',
          },
          hyperlink: {
            link: '',
            hyperlinkOpenState: 'NewTab',
            content: '',
            textDecoration: 'None',
          },
          constraints: 4,
          visibility: true,
          rotateAngle: 0,
          margin: { right: 0, bottom: 0, left: 0, top: 0 },
          horizontalAlignment: 'Center',
          verticalAlignment: 'Center',
          offset: { x: 0.5, y: 0.5 },
        },
      ],
      style: {
        fill: '#fbfdc5',
        strokeColor: '#797979',
        gradient: { type: 'None' },
        strokeWidth: 1,
        strokeDashArray: '',
        opacity: 1,
      },
      zIndex: 1,
      container: null,
      visible: true,
      horizontalAlignment: 'Left',
      verticalAlignment: 'Top',
      backgroundColor: 'transparent',
      borderColor: 'none',
      borderWidth: 0,
      rotateAngle: 0,
      pivot: { x: 0.5, y: 0.5 },
      margin: {},
      flip: 'None',
      wrapper: {
        actualSize: { width: 100, height: 50 },
        offsetX: 250,
        offsetY: 160,
      },
      constraints: 5240814,
      isExpanded: true,
      expandIcon: { shape: 'None' },
      fixedUserHandles: [],
      inEdges: ['connector1', 'connector7'],
      outEdges: ['connector2'],
      parentId: '',
      processId: '',
      umlIndex: -1,
      isPhase: false,
      isLane: false,
    },
    {
      shape: { type: 'Flow', shape: 'Decision' },
      ports: [],
      id: 'Ready',
      height: 80,
      width: 100,
      offsetX: 250,
      offsetY: 260,
      annotations: [
        {
          id: 'uawaH',
          content: 'Ready to Get Up?',
          margin: { top: 10, left: 10, right: 10, bottom: 10 },
          annotationType: 'String',
          style: {
            strokeWidth: 0,
            strokeColor: 'transparent',
            fill: 'transparent',
            bold: false,
            textWrapping: 'WrapWithOverflow',
            color: 'black',
            whiteSpace: 'CollapseSpace',
            fontFamily: 'Arial',
            fontSize: 12,
            italic: false,
            opacity: 1,
            strokeDashArray: '',
            textAlign: 'Center',
            textOverflow: 'Wrap',
            textDecoration: 'None',
          },
          hyperlink: {
            link: '',
            hyperlinkOpenState: 'NewTab',
            content: '',
            textDecoration: 'None',
          },
          constraints: 4,
          visibility: true,
          rotateAngle: 0,
          horizontalAlignment: 'Center',
          verticalAlignment: 'Center',
          offset: { x: 0.5, y: 0.5 },
        },
      ],
      style: {
        fill: '#c5efaf',
        strokeColor: '#797979',
        gradient: { type: 'None' },
        strokeWidth: 1,
        strokeDashArray: '',
        opacity: 1,
      },
      zIndex: 2,
      container: null,
      visible: true,
      horizontalAlignment: 'Left',
      verticalAlignment: 'Top',
      backgroundColor: 'transparent',
      borderColor: 'none',
      borderWidth: 0,
      rotateAngle: 0,
      pivot: { x: 0.5, y: 0.5 },
      margin: {},
      flip: 'None',
      wrapper: {
        actualSize: { width: 100, height: 80 },
        offsetX: 250,
        offsetY: 260,
      },
      constraints: 5240814,
      isExpanded: true,
      expandIcon: { shape: 'None' },
      fixedUserHandles: [],
      inEdges: ['connector2'],
      outEdges: ['connector3', 'connector5'],
      parentId: '',
      processId: '',
      umlIndex: -1,
      isPhase: false,
      isLane: false,
    },
    {
      shape: { type: 'Flow', shape: 'Process' },
      ports: [],
      id: 'Climb',
      height: 50,
      width: 100,
      offsetX: 250,
      offsetY: 370,
      annotations: [
        {
          id: 'ItO4O',
          content: 'Climb Out of Bed',
          annotationType: 'String',
          style: {
            strokeWidth: 0,
            strokeColor: 'transparent',
            fill: 'transparent',
            bold: false,
            textWrapping: 'WrapWithOverflow',
            color: 'black',
            whiteSpace: 'CollapseSpace',
            fontFamily: 'Arial',
            fontSize: 12,
            italic: false,
            opacity: 1,
            strokeDashArray: '',
            textAlign: 'Center',
            textOverflow: 'Wrap',
            textDecoration: 'None',
          },
          hyperlink: {
            link: '',
            hyperlinkOpenState: 'NewTab',
            content: '',
            textDecoration: 'None',
          },
          constraints: 4,
          visibility: true,
          rotateAngle: 0,
          margin: { right: 0, bottom: 0, left: 0, top: 0 },
          horizontalAlignment: 'Center',
          verticalAlignment: 'Center',
          offset: { x: 0.5, y: 0.5 },
        },
      ],
      style: {
        fill: '#fbfdc5',
        strokeColor: '#797979',
        gradient: { type: 'None' },
        strokeWidth: 1,
        strokeDashArray: '',
        opacity: 1,
      },
      zIndex: 3,
      container: null,
      visible: true,
      horizontalAlignment: 'Left',
      verticalAlignment: 'Top',
      backgroundColor: 'transparent',
      borderColor: 'none',
      borderWidth: 0,
      rotateAngle: 0,
      pivot: { x: 0.5, y: 0.5 },
      margin: {},
      flip: 'None',
      wrapper: {
        actualSize: { width: 100, height: 50 },
        offsetX: 250,
        offsetY: 370,
      },
      constraints: 5240814,
      isExpanded: true,
      expandIcon: { shape: 'None' },
      fixedUserHandles: [],
      inEdges: ['connector3'],
      outEdges: ['connector4'],
      parentId: '',
      processId: '',
      umlIndex: -1,
      isPhase: false,
      isLane: false,
    },
    {
      shape: { type: 'Flow', shape: 'Terminator' },
      ports: [],
      id: 'End',
      height: 50,
      width: 100,
      offsetX: 250,
      offsetY: 460,
      annotations: [
        {
          id: 'dGsie',
          content: 'End',
          annotationType: 'String',
          style: {
            strokeWidth: 0,
            strokeColor: 'transparent',
            fill: 'transparent',
            bold: false,
            textWrapping: 'WrapWithOverflow',
            color: 'black',
            whiteSpace: 'CollapseSpace',
            fontFamily: 'Arial',
            fontSize: 12,
            italic: false,
            opacity: 1,
            strokeDashArray: '',
            textAlign: 'Center',
            textOverflow: 'Wrap',
            textDecoration: 'None',
          },
          hyperlink: {
            link: '',
            hyperlinkOpenState: 'NewTab',
            content: '',
            textDecoration: 'None',
          },
          constraints: 4,
          visibility: true,
          rotateAngle: 0,
          margin: { right: 0, bottom: 0, left: 0, top: 0 },
          horizontalAlignment: 'Center',
          verticalAlignment: 'Center',
          offset: { x: 0.5, y: 0.5 },
        },
      ],
      style: {
        fill: '#d0f0f1',
        strokeColor: '#797979',
        gradient: { type: 'None' },
        strokeWidth: 1,
        strokeDashArray: '',
        opacity: 1,
      },
      zIndex: 4,
      container: null,
      visible: true,
      horizontalAlignment: 'Left',
      verticalAlignment: 'Top',
      backgroundColor: 'transparent',
      borderColor: 'none',
      borderWidth: 0,
      rotateAngle: 0,
      pivot: { x: 0.5, y: 0.5 },
      margin: {},
      flip: 'None',
      wrapper: {
        actualSize: { width: 100, height: 50 },
        offsetX: 250,
        offsetY: 460,
      },
      constraints: 5240814,
      isExpanded: true,
      expandIcon: { shape: 'None' },
      fixedUserHandles: [],
      inEdges: ['connector4'],
      outEdges: [],
      parentId: '',
      processId: '',
      umlIndex: -1,
      isPhase: false,
      isLane: false,
    },
    {
      shape: { type: 'Flow', shape: 'Delay' },
      ports: [],
      id: 'Relay',
      height: 50,
      width: 100,
      offsetX: 450,
      offsetY: 160,
      annotations: [
        {
          id: 'Ept4T',
          content: 'Relay',
          annotationType: 'String',
          style: {
            strokeWidth: 0,
            strokeColor: 'transparent',
            fill: 'transparent',
            bold: false,
            textWrapping: 'WrapWithOverflow',
            color: 'black',
            whiteSpace: 'CollapseSpace',
            fontFamily: 'Arial',
            fontSize: 12,
            italic: false,
            opacity: 1,
            strokeDashArray: '',
            textAlign: 'Center',
            textOverflow: 'Wrap',
            textDecoration: 'None',
          },
          hyperlink: {
            link: '',
            hyperlinkOpenState: 'NewTab',
            content: '',
            textDecoration: 'None',
          },
          constraints: 4,
          visibility: true,
          rotateAngle: 0,
          margin: { right: 0, bottom: 0, left: 0, top: 0 },
          horizontalAlignment: 'Center',
          verticalAlignment: 'Center',
          offset: { x: 0.5, y: 0.5 },
        },
      ],
      style: {
        fill: '#f8eee5',
        strokeColor: '#797979',
        gradient: { type: 'None' },
        strokeWidth: 1,
        strokeDashArray: '',
        opacity: 1,
      },
      zIndex: 5,
      container: null,
      visible: true,
      horizontalAlignment: 'Left',
      verticalAlignment: 'Top',
      backgroundColor: 'transparent',
      borderColor: 'none',
      borderWidth: 0,
      rotateAngle: 0,
      pivot: { x: 0.5, y: 0.5 },
      margin: {},
      flip: 'None',
      wrapper: {
        actualSize: { width: 100, height: 50 },
        offsetX: 450,
        offsetY: 160,
      },
      constraints: 5240814,
      isExpanded: true,
      expandIcon: { shape: 'None' },
      fixedUserHandles: [],
      inEdges: ['connector6'],
      outEdges: ['connector7'],
      parentId: '',
      processId: '',
      umlIndex: -1,
      isPhase: false,
      isLane: false,
    },
    {
      shape: { type: 'Flow', shape: 'Process' },
      ports: [],
      id: 'Hit',
      height: 50,
      width: 100,
      offsetX: 450,
      offsetY: 260,
      annotations: [
        {
          id: 'XHoI1',
          content: 'Hit Snooze Button',
          margin: { top: 10, left: 10, right: 10, bottom: 10 },
          annotationType: 'String',
          style: {
            strokeWidth: 0,
            strokeColor: 'transparent',
            fill: 'transparent',
            bold: false,
            textWrapping: 'WrapWithOverflow',
            color: 'black',
            whiteSpace: 'CollapseSpace',
            fontFamily: 'Arial',
            fontSize: 12,
            italic: false,
            opacity: 1,
            strokeDashArray: '',
            textAlign: 'Center',
            textOverflow: 'Wrap',
            textDecoration: 'None',
          },
          hyperlink: {
            link: '',
            hyperlinkOpenState: 'NewTab',
            content: '',
            textDecoration: 'None',
          },
          constraints: 4,
          visibility: true,
          rotateAngle: 0,
          horizontalAlignment: 'Center',
          verticalAlignment: 'Center',
          offset: { x: 0.5, y: 0.5 },
        },
      ],
      style: {
        fill: '#fbfdc5',
        strokeColor: '#797979',
        gradient: { type: 'None' },
        strokeWidth: 1,
        strokeDashArray: '',
        opacity: 1,
      },
      zIndex: 6,
      container: null,
      visible: true,
      horizontalAlignment: 'Left',
      verticalAlignment: 'Top',
      backgroundColor: 'transparent',
      borderColor: 'none',
      borderWidth: 0,
      rotateAngle: 0,
      pivot: { x: 0.5, y: 0.5 },
      margin: {},
      flip: 'None',
      wrapper: {
        actualSize: { width: 100, height: 50 },
        offsetX: 450,
        offsetY: 260,
      },
      constraints: 5240814,
      isExpanded: true,
      expandIcon: { shape: 'None' },
      fixedUserHandles: [],
      inEdges: ['connector5'],
      outEdges: ['connector6'],
      parentId: '',
      processId: '',
      umlIndex: -1,
      isPhase: false,
      isLane: false,
    },
  ],
  snapSettings: {
    horizontalGridlines: {
      lineColor: '#e0e0e0',
      lineIntervals: [
        1,
        9,
        0.25,
        9.75,
        0.25,
        9.75,
        0.25,
        9.75,
        0.25,
        9.75,
        0.25,
        9.75,
        0.25,
        9.75,
        0.25,
        9.75,
        0.25,
        9.75,
        0.25,
        9.75,
      ],
      snapIntervals: [20],
      lineDashArray: '',
    },
    verticalGridlines: {
      lineColor: '#e0e0e0',
      lineIntervals: [
        1,
        9,
        0.25,
        9.75,
        0.25,
        9.75,
        0.25,
        9.75,
        0.25,
        9.75,
        0.25,
        9.75,
        0.25,
        9.75,
        0.25,
        9.75,
        0.25,
        9.75,
        0.25,
        9.75,
      ],
      snapIntervals: [20],
      lineDashArray: '',
    },
    constraints: 31,
    gridType: 'Lines',
  },
  connectors: [
    {
      shape: { type: 'None' },
      id: 'connector1',
      sourceID: 'Start',
      targetID: 'Alarm',
      annotations: [],
      zIndex: 7,
      targetDecorator: {
        shape: 'Arrow',
        height: 5,
        width: 5,
        style: {
          fill: '#797979',
          strokeColor: '#797979',
          strokeWidth: 1,
          strokeDashArray: '',
          opacity: 1,
          gradient: { type: 'None' },
        },
        pivot: { x: 0, y: 0.5 },
      },
      style: {
        strokeWidth: 1,
        strokeColor: '#797979',
        fill: 'transparent',
        strokeDashArray: '',
        opacity: 1,
        gradient: { type: 'None' },
      },
      segments: [{ type: 'Straight', point: { x: 0, y: 0 } }],
      sourcePortID: '',
      targetPortID: '',
      type: 'Straight',
      sourcePadding: 0,
      targetPadding: 0,
      targetPoint: { x: 250, y: 135 },
      connectorSpacing: 13,
      sourcePoint: { x: 250, y: 85 },
      sourceDecorator: {
        shape: 'None',
        width: 10,
        height: 10,
        pivot: { x: 0, y: 0.5 },
        style: {
          fill: 'black',
          strokeColor: 'black',
          strokeWidth: 1,
          strokeDashArray: '',
          opacity: 1,
          gradient: { type: 'None' },
        },
      },
      cornerRadius: 0,
      wrapper: {
        actualSize: { width: 0, height: 50 },
        offsetX: 250,
        offsetY: 110,
      },
      fixedUserHandles: [],
      visible: true,
      parentId: '',
    },
    {
      shape: { type: 'None' },
      id: 'connector2',
      sourceID: 'Alarm',
      targetID: 'Ready',
      annotations: [],
      zIndex: 8,
      targetDecorator: {
        shape: 'Arrow',
        height: 5,
        width: 5,
        style: {
          fill: '#797979',
          strokeColor: '#797979',
          strokeWidth: 1,
          strokeDashArray: '',
          opacity: 1,
          gradient: { type: 'None' },
        },
        pivot: { x: 0, y: 0.5 },
      },
      style: {
        strokeWidth: 1,
        strokeColor: '#797979',
        fill: 'transparent',
        strokeDashArray: '',
        opacity: 1,
        gradient: { type: 'None' },
      },
      segments: [{ type: 'Straight', point: { x: 0, y: 0 } }],
      sourcePortID: '',
      targetPortID: '',
      type: 'Straight',
      sourcePadding: 0,
      targetPadding: 0,
      targetPoint: { x: 250, y: 222.07 },
      connectorSpacing: 13,
      sourcePoint: { x: 250, y: 185 },
      sourceDecorator: {
        shape: 'None',
        width: 10,
        height: 10,
        pivot: { x: 0, y: 0.5 },
        style: {
          fill: 'black',
          strokeColor: 'black',
          strokeWidth: 1,
          strokeDashArray: '',
          opacity: 1,
          gradient: { type: 'None' },
        },
      },
      cornerRadius: 0,
      wrapper: {
        actualSize: { width: 0, height: 37.06999999999999 },
        offsetX: 250,
        offsetY: 203.535,
      },
      fixedUserHandles: [],
      visible: true,
      parentId: '',
    },
    {
      shape: { type: 'None' },
      id: 'connector3',
      sourceID: 'Ready',
      targetID: 'Climb',
      annotations: [
        {
          id: 'dKJXU',
          content: 'Yes',
          style: {
            strokeWidth: 0,
            strokeColor: 'transparent',
            fill: 'white',
            strokeDashArray: '',
            opacity: 1,
            gradient: { type: 'None' },
            fontSize: 12,
            fontFamily: 'Arial',
            textOverflow: 'Wrap',
            textDecoration: 'None',
            whiteSpace: 'CollapseSpace',
            textWrapping: 'WrapWithOverflow',
            textAlign: 'Center',
            color: 'black',
            italic: false,
            bold: false,
          },
          annotationType: 'String',
          constraints: 4,
          visibility: true,
          rotateAngle: 0,
          horizontalAlignment: 'Center',
          verticalAlignment: 'Center',
          margin: { left: 0, right: 0, bottom: 0, top: 0 },
          offset: 0.5,
          alignment: 'Center',
          segmentAngle: false,
        },
      ],
      zIndex: 9,
      targetDecorator: {
        shape: 'Arrow',
        height: 5,
        width: 5,
        style: {
          fill: '#797979',
          strokeColor: '#797979',
          strokeWidth: 1,
          strokeDashArray: '',
          opacity: 1,
          gradient: { type: 'None' },
        },
        pivot: { x: 0, y: 0.5 },
      },
      style: {
        strokeWidth: 1,
        strokeColor: '#797979',
        fill: 'transparent',
        strokeDashArray: '',
        opacity: 1,
        gradient: { type: 'None' },
      },
      segments: [{ type: 'Straight', point: { x: 0, y: 0 } }],
      sourcePortID: '',
      targetPortID: '',
      type: 'Straight',
      sourcePadding: 0,
      targetPadding: 0,
      targetPoint: { x: 250, y: 345 },
      connectorSpacing: 13,
      sourcePoint: { x: 250, y: 296.99 },
      sourceDecorator: {
        shape: 'None',
        width: 10,
        height: 10,
        pivot: { x: 0, y: 0.5 },
        style: {
          fill: 'black',
          strokeColor: 'black',
          strokeWidth: 1,
          strokeDashArray: '',
          opacity: 1,
          gradient: { type: 'None' },
        },
      },
      cornerRadius: 0,
      wrapper: {
        actualSize: { width: 0, height: 48.00999999999999 },
        offsetX: 250,
        offsetY: 320.995,
      },
      fixedUserHandles: [],
      visible: true,
      parentId: '',
    },
    {
      shape: { type: 'None' },
      id: 'connector4',
      sourceID: 'Climb',
      targetID: 'End',
      annotations: [],
      zIndex: 10,
      targetDecorator: {
        shape: 'Arrow',
        height: 5,
        width: 5,
        style: {
          fill: '#797979',
          strokeColor: '#797979',
          strokeWidth: 1,
          strokeDashArray: '',
          opacity: 1,
          gradient: { type: 'None' },
        },
        pivot: { x: 0, y: 0.5 },
      },
      style: {
        strokeWidth: 1,
        strokeColor: '#797979',
        fill: 'transparent',
        strokeDashArray: '',
        opacity: 1,
        gradient: { type: 'None' },
      },
      segments: [{ type: 'Straight', point: { x: 0, y: 0 } }],
      sourcePortID: '',
      targetPortID: '',
      type: 'Straight',
      sourcePadding: 0,
      targetPadding: 0,
      targetPoint: { x: 250, y: 435 },
      connectorSpacing: 13,
      sourcePoint: { x: 250, y: 395 },
      sourceDecorator: {
        shape: 'None',
        width: 10,
        height: 10,
        pivot: { x: 0, y: 0.5 },
        style: {
          fill: 'black',
          strokeColor: 'black',
          strokeWidth: 1,
          strokeDashArray: '',
          opacity: 1,
          gradient: { type: 'None' },
        },
      },
      cornerRadius: 0,
      wrapper: {
        actualSize: { width: 0, height: 40 },
        offsetX: 250,
        offsetY: 415,
      },
      fixedUserHandles: [],
      visible: true,
      parentId: '',
    },
    {
      shape: { type: 'None' },
      id: 'connector5',
      sourceID: 'Ready',
      targetID: 'Hit',
      annotations: [
        {
          id: 'LGPg8',
          content: 'No',
          style: {
            strokeWidth: 0,
            strokeColor: 'transparent',
            fill: 'white',
            strokeDashArray: '',
            opacity: 1,
            gradient: { type: 'None' },
            fontSize: 12,
            fontFamily: 'Arial',
            textOverflow: 'Wrap',
            textDecoration: 'None',
            whiteSpace: 'CollapseSpace',
            textWrapping: 'WrapWithOverflow',
            textAlign: 'Center',
            color: 'black',
            italic: false,
            bold: false,
          },
          annotationType: 'String',
          constraints: 4,
          visibility: true,
          rotateAngle: 0,
          horizontalAlignment: 'Center',
          verticalAlignment: 'Center',
          margin: { left: 0, right: 0, bottom: 0, top: 0 },
          offset: 0.5,
          alignment: 'Center',
          segmentAngle: false,
        },
      ],
      zIndex: 11,
      targetDecorator: {
        shape: 'Arrow',
        height: 5,
        width: 5,
        style: {
          fill: '#797979',
          strokeColor: '#797979',
          strokeWidth: 1,
          strokeDashArray: '',
          opacity: 1,
          gradient: { type: 'None' },
        },
        pivot: { x: 0, y: 0.5 },
      },
      style: {
        strokeWidth: 1,
        strokeColor: '#797979',
        fill: 'transparent',
        strokeDashArray: '',
        opacity: 1,
        gradient: { type: 'None' },
      },
      segments: [{ type: 'Straight', point: { x: 0, y: 0 } }],
      sourcePortID: '',
      targetPortID: '',
      type: 'Straight',
      sourcePadding: 0,
      targetPadding: 0,
      targetPoint: { x: 400, y: 260 },
      connectorSpacing: 13,
      sourcePoint: { x: 300, y: 260 },
      sourceDecorator: {
        shape: 'None',
        width: 10,
        height: 10,
        pivot: { x: 0, y: 0.5 },
        style: {
          fill: 'black',
          strokeColor: 'black',
          strokeWidth: 1,
          strokeDashArray: '',
          opacity: 1,
          gradient: { type: 'None' },
        },
      },
      cornerRadius: 0,
      wrapper: {
        actualSize: { width: 100, height: 0 },
        offsetX: 350,
        offsetY: 260,
      },
      fixedUserHandles: [],
      visible: true,
      parentId: '',
    },
    {
      shape: { type: 'None' },
      id: 'connector6',
      sourceID: 'Hit',
      targetID: 'Relay',
      annotations: [],
      zIndex: 12,
      targetDecorator: {
        shape: 'Arrow',
        height: 5,
        width: 5,
        style: {
          fill: '#797979',
          strokeColor: '#797979',
          strokeWidth: 1,
          strokeDashArray: '',
          opacity: 1,
          gradient: { type: 'None' },
        },
        pivot: { x: 0, y: 0.5 },
      },
      style: {
        strokeWidth: 1,
        strokeColor: '#797979',
        fill: 'transparent',
        strokeDashArray: '',
        opacity: 1,
        gradient: { type: 'None' },
      },
      segments: [{ type: 'Straight', point: { x: 0, y: 0 } }],
      sourcePortID: '',
      targetPortID: '',
      type: 'Straight',
      sourcePadding: 0,
      targetPadding: 0,
      targetPoint: { x: 450, y: 185 },
      connectorSpacing: 13,
      sourcePoint: { x: 450, y: 235 },
      sourceDecorator: {
        shape: 'None',
        width: 10,
        height: 10,
        pivot: { x: 0, y: 0.5 },
        style: {
          fill: 'black',
          strokeColor: 'black',
          strokeWidth: 1,
          strokeDashArray: '',
          opacity: 1,
          gradient: { type: 'None' },
        },
      },
      cornerRadius: 0,
      wrapper: {
        actualSize: { width: 0, height: 50 },
        offsetX: 450,
        offsetY: 210,
      },
      fixedUserHandles: [],
      visible: true,
      parentId: '',
    },
    {
      shape: { type: 'None' },
      id: 'connector7',
      sourceID: 'Relay',
      targetID: 'Alarm',
      annotations: [],
      zIndex: 13,
      targetDecorator: {
        shape: 'Arrow',
        height: 5,
        width: 5,
        style: {
          fill: '#797979',
          strokeColor: '#797979',
          strokeWidth: 1,
          strokeDashArray: '',
          opacity: 1,
          gradient: { type: 'None' },
        },
        pivot: { x: 0, y: 0.5 },
      },
      style: {
        strokeWidth: 1,
        strokeColor: '#797979',
        fill: 'transparent',
        strokeDashArray: '',
        opacity: 1,
        gradient: { type: 'None' },
      },
      segments: [{ type: 'Straight', point: { x: 0, y: 0 } }],
      sourcePortID: '',
      targetPortID: '',
      type: 'Straight',
      sourcePadding: 0,
      targetPadding: 0,
      targetPoint: { x: 300, y: 160 },
      connectorSpacing: 13,
      sourcePoint: { x: 400, y: 160 },
      sourceDecorator: {
        shape: 'None',
        width: 10,
        height: 10,
        pivot: { x: 0, y: 0.5 },
        style: {
          fill: 'black',
          strokeColor: 'black',
          strokeWidth: 1,
          strokeDashArray: '',
          opacity: 1,
          gradient: { type: 'None' },
        },
      },
      cornerRadius: 0,
      wrapper: {
        actualSize: { width: 100, height: 0 },
        offsetX: 350,
        offsetY: 160,
      },
      fixedUserHandles: [],
      visible: true,
      parentId: '',
    },
  ],
  getConnectorDefaults: {},
  dragEnter: {},
  enableRtl: false,
  locale: 'en',
  enablePersistence: false,
  scrollSettings: {
    viewPortWidth: 832,
    viewPortHeight: 645,
    currentZoom: 1,
    horizontalOffset: 0,
    verticalOffset: 0,
    padding: { left: 0, right: 0, top: 0, bottom: 0 },
    scrollLimit: 'Diagram',
  },
  rulerSettings: { showRulers: false },
  backgroundColor: 'transparent',
  dataSourceSettings: {
    crudAction: { read: '' },
    dataManager: null,
    dataSource: null,
  },
  mode: 'SVG',
  layers: [
    {
      id: 'default_layer',
      visible: true,
      lock: false,
      objects: [
        'Start',
        'Alarm',
        'Ready',
        'Climb',
        'End',
        'Relay',
        'Hit',
        'connector1',
        'connector2',
        'connector3',
        'connector4',
        'connector5',
        'connector6',
        'connector7',
      ],
      zIndex: 0,
      objectZIndex: 13,
    },
  ],
  diagramSettings: { inversedAlignment: true },
  constraints: 500,
  layout: { type: 'None', enableRouting: false },
  pageSettings: {
    boundaryConstraints: 'Infinity',
    orientation: 'Landscape',
    height: null,
    width: null,
    background: { source: '', color: 'transparent' },
    showPageBreaks: false,
    fitOptions: { canFit: false },
  },
  selectedItems: {
    nodes: [],
    connectors: [],
    wrapper: null,
    constraints: 16382,
    selectedObjects: [],
    userHandles: [],
    rotateAngle: 0,
  },
  basicElements: [],
  tooltip: { content: '' },
  commandManager: { commands: [] },
  tool: 3,
  customCursor: [],
  serializationSettings: { preventDefaults: false },
  version: 17.1,
};
